### ISSUE TITLE
Make launchers for all software that doesn't have a menu representation

### ISSUE THREAD

**Issue by MatthewVi** [GoTeamEpsilon/PersonaScripts#23]

**Comment by kofiav** [comment]
Hey, I guess I have two questions. Which specific applications don't have a menu representation?

Also I'm thinking of including the `.desktop` files in `personas/general` and then we will put a line in `general.sh` that copies them to `/usr/share/applications`. Is this what you had in mind?

**Comment by MatthewVi** [comment]
@kofiav sorry for the delay.

> Which specific applications don't have a menu representation?

- https://github.com/GoTeamEpsilon/System/blob/master/personas/engineer/engineer.sh#L824-L830
- https://github.com/GoTeamEpsilon/System/blob/master/personas/creative/creative.sh#L104
- https://github.com/GoTeamEpsilon/System/blob/master/personas/clinician/clinician.sh#L29-L33
- https://github.com/GoTeamEpsilon/System/blob/master/personas/clinician/clinician.sh#L37-L38 (currently, these are put into folders on the desktop - would love to have them elsewhere with a menu representation)

> Also I'm thinking of including the .desktop files in personas/general

Good idea, but keep them within their own persona folder just to "separate concerns". Let me know if I'm missing something here, though.

> Is this what you had in mind?

Sounds like it. Let me know what you come up with!

Thanks!!!

**Comment by kofiav** [comment]
@MatthewVi I'm looking at this right now. Looks like there's been lots of updates in the past week or so.

**Comment by MatthewVi** [comment]
https://github.com/GoTeamEpsilon/PersonaScripts/commit/4aa239cfbe9d75e1ad1500fa5f8da17a851b9c06
