### ISSUE TITLE
New Repo Name

### ISSUE THREAD

**Issue by MatthewVi** [GoTeamEpsilon/PersonaScripts#47]
@andremillet, @d3sandoval,

I changed the repo name after getting some feedback on the confusion of the name. In reality, all this solution is is a bunch of shell scripts that make a computer useful.

![image](https://user-images.githubusercontent.com/1715206/46175036-a4b52880-c278-11e8-8728-ad8ef7c185aa.png)

I chose to use a mono font for the word "Scripts" to be more computer-y.

Let me know if you have a better name :)

**Comment by andremillet** [comment]
it is fine for me.
thanks

*André Millet*



Em qui, 27 de set de 2018 às 18:14, mvim <notifications@github.com>
escreveu:
